ALTER TABLE EMPLOYEE1
ADD CONSTRAINT AGE_LIMIT CHECK(AGE<65);

INSERT INTO EMPLOYEE1(SSN, FNAME, M, LNAME, ADDRESS, PHONE, AGE, SEX, JOBTYPE, ASTYPE, ETYPE, SHIFT, POSITION, AP_NAME)
VALUES(123456799,'RAM','M','SHARMA','731 HILL TOWN, ARLINGTON, TX',4356789365, 66, 'M','ADMINISTRATIVE SUPPORT','RECEPTIONIST','','','','Louisville	International Airport');
