--procedure1
 SET SERVEROUTPUT ON
 exec DFWECONOMYPASSENGERS();
 
 
--procedure2
SET SERVEROUTPUT ON 
exec FLIGHTSBYSTATUS('Delayed');
-- or--
SET SERVEROUTPUT ON 
exec FLIGHTSBYSTATUS('On-time');

--trigger1
UPDATE FLIGHT
SET STATUS='Delayed'
WHERE DESTINATION='FRA'
AND SOURCE='SFO'

--trigger 3
UPDATE TICKET2
SET PRICE=150000
WHERE DATE_OF_BOOKING ='11-NOV-16'
AND SOURCE='BOM'
AND DESTINATION='DFW'
AND CLASS='ECONOMY'

--business rule1
INSERT INTO TICKET1(TICKET_NUMBER, SOURCE, DESTINATION, DATE_OF_BOOKING, DATE_OF_CANCELLATION, DATE_OF_TRAVEL, SEATNO, CLASS, PID, PASSPORTNO)
VALUES(00112341111221,'BOM','DFW','11-MAY-16','','15-DEC-16','32A','ECONOMY',1,'A12345678');

--business rule2
INSERT INTO EMPLOYEE1(SSN, FNAME, M, LNAME, ADDRESS, PHONE, AGE, SEX, JOBTYPE, ASTYPE, ETYPE, SHIFT, POSITION, AP_NAME)
VALUES(123456799,'RAM','M','SHARMA','731 HILL TOWN, ARLINGTON, TX',4356789365, 66, 'M','ADMINISTRATIVE SUPPORT','RECEPTIONIST','','','','Louisville	International Airport');
