CREATE OR REPLACE TRIGGER UPDATEDSalary AFTER
  INSERT OR
  UPDATE OF SALARY ON EMPLOYEE2
  FOR EACH ROW
DECLARE 
JOBTYPE EMPLOYEE2.JOBTYPE%TYPE;
BEGIN
  CASE
    WHEN (JOBTYPE= 'Administrative Support') THEN
      UPDATE EMPLOYEE2 SET SALARY=SALARY+SALARY*.10;
    WHEN (JOBTYPE= 'ENGINEER') THEN
      UPDATE EMPLOYEE2 SET SALARY=SALARY+SALARY*.05;
    WHEN (JOBTYPE= 'TRAFFIC MONITOR') THEN
      UPDATE EMPLOYEE2 SET SALARY=SALARY+SALARY*.25;
    WHEN (JOBTYPE= 'AIRPORT AUTHORITY') THEN
      UPDATE EMPLOYEE2 SET SALARY=SALARY+SALARY*.45;
    END CASE; 
END;